### ISSUE TITLE
Extension breaking search on outlook.live.com

### ISSUE THREAD

**Issue by brlala** [iamadamdev/bypass-paywalls-chrome#438] opened 2019-12-14 13:18 UTC
Issue: Making a search on outlook.live.com mailbox will refresh the page and clear the search results.
Steps to reproduce:
1. Install the tweak
2. Login to Outlook Mailbox
3. Search for any keyword and confirm the search query.

Additional Note on the issue: Your account will remain login, just that you cannot make any search due to the issue above.

**Comment by magnolia1234** [comment] 2019-12-14 17:02
Not reproducable for me.
Looks like random refresh by adblcoker like uBlock Origin.

**Comment by brlala** [comment] 2019-12-15 04:45
I managed to reproduce it reliably, the issue seems to happen if I have "Medium" selected. The steps are done with cache and cookies cleared and all extensions disabled except BypassPaywalls and LastPass.

**Comment by brlala** [comment] 2019-12-15 05:44
[https://youtu.be/ZauQnC0BUDM](url) I've uploaded a video demonstrating the effect with "Medium" selected and without. The bug happens when I switch to the **Others** tab too.

**Comment by magnolia1234** [comment] 2019-12-15 11:46
If possible test fix in PR #431

**Comment by brlala** [comment] 2019-12-15 13:42
thanks for the heads up, I've removed the video from YouTube. Can confirm the issue is fixed in PR#431

**Comment by magnolia1234** [comment] 2019-12-15 18:01
Yes, I figured so.
Probably a more precise identification of Medium sites should fix the problem.
Btw I don't get a notification if you update your comment (better add a new one).

**Comment by magnolia1234** [comment] 2019-12-15 18:42
Properly fixed now for Medium-content not on Medium-client sites (e.g. Outlook/Gmail).

**Closed** 2020-02-29 22:53 UTC
