### ISSUE TITLE
Webpage The Athletic

### ISSUE THREAD

**Issue by juanmsola** [iamadamdev/bypass-paywalls-chrome#872] opened 2020-09-03 18:15 UTC
Hi,

First, thanks for this amazing extension, it was the discovery of the year. Really really helpful

On the other hand, a few days ago the extension stopped working with https://theathletic.com/ and https://theathletic.co.uk/, I don't know what could happen. If you can check would be great.

Thanks again and be well

###
1. Make sure uBlock Origin is installed.
2. Bypass Paywalls version?
3. Chrome or Firefox?
4. Paste the article URL for the site you are having issues with.
5. Describe the issue.

Requests not following these instructions will be ignored.
###

**Comment by Nashdiz** [comment] 2020-09-03 18:52
duplicate of issue #859

**Closed** 2020-09-03 19:12 UTC
