### ISSUE TITLE
Chrome Extension 

### ISSUE THREAD

**Issue by kchio0331** [iamadamdev/bypass-paywalls-chrome#892] opened 2020-09-15 16:51 UTC
Hello, 

I am trying to add your extension to Chrome, but a message keeps showing and I cannot add it. Do you know the reason? Do you have 
a solution? Please see my snapshot. Thank you. 

![D23F20CB-7F08-495F-9687-1B14CA29B8C7](https://user-images.githubusercontent.com/59630570/93240517-0bb79a80-f739-11ea-9ea6-f22c2fac8b3a.jpeg)

**Comment by Recol** [comment] 2020-09-15 18:15
Chrome browsers cannot load in ZIP files which are held by corporate management, this requires the developer release of Chrome specifically to load in from an unpackaged format, there is nothing you can do to resolve this.

**Comment by Recol** [comment] 2020-09-15 18:17
Duplicate of #822

**Comment by iamadamdev** [comment] 2020-09-15 19:38
You need to manually unzip the file yourself, and then drag the resulting folder into the chrome extensions page.

**Comment by kchio0331** [comment] 2020-09-15 19:58
How can I manually unzip the folder? Please advise. Thank you.

**Comment by iamadamdev** [comment] 2020-09-15 20:10
https://www.lmgtfy.com/?q=how+to+unzip+a+file

**Closed by iamadamdev** 2020-09-15 20:10 UTC
