### ISSUE TITLE
After ~15mins, all websites will fail to load

### ISSUE THREAD

**Issue by oredbored** [iamadamdev/bypass-paywalls-chrome#578] opened 2020-04-24 02:05 UTC
Hello,

When I enable the extension, it works fine for around 15 minutes and then suddenly chrome will stop loading any website. it will just be stuck with the page loading icon, as though the internet is out. As soon as I disable the bypass-paywalls extension then everything will be normal again. And if I re-enable it, again it will work for 15 minutes before bugging out. 

I have tried re-installing it the extesion. Have also tried unticking General Paywall-Bypass.

I am open to any suggestions and would be happy to trouble-shoot.

Thanks

**Comment by iamadamdev** [comment] 2020-04-24 02:34
How about try visiting 3 different articles from 3 main sites and staying on those for 15 min and then see if it happens.
Maybe try wsj.com, economist.com, and hbr.org

**Comment by iamadamdev** [comment] 2020-04-24 02:36
If you can reproduce the issue, please post a screenshot of what your Google Chrome task manager looks like (shift+esc)

**Comment by oredbored** [comment] 2020-04-24 02:38
Ok, I'll try that now and report back.

**Comment by oredbored** [comment] 2020-04-24 03:30
So, I just spent 45 minutes browsing only wsj, economist and hbr, and was not able to reproduce the issue under those conditions. I'll now try to reproduce the issue again with general browsing and post the screenshot.

**Comment by oredbored** [comment] 2020-04-25 03:06
Here is the screenshot. It took many hours to reproduce this time. 
![screenshot](https://user-images.githubusercontent.com/64238189/80217003-16429c00-8693-11ea-9368-84482bff9edc.png)
And here is a screenshot I took after disabling the extension:
![after](https://user-images.githubusercontent.com/64238189/80217160-53a72980-8693-11ea-9fd7-a20ed919381d.png)

**Comment by iamadamdev** [comment] 2020-04-25 05:16
Actually I meant Google Chrome task manager (shift+esc) not the Windows task manager.
In the Google task manager we can see exactly what extension it was and memory footprint, cpu usage, network, etc.

**Comment by jrbarrick** [comment] 2020-04-26 06:51
Oddly enough, I've started hitting this same problem today, but in my case I can trigger it every time with this page:
https://www.harveynorman.com.au/berwick-3-5-seater-fabric-sofa.html

Chrome Task Manager shows nothing out of the ordinary, other than Chrome itself using a lot of CPU.  Windows Task Manger shows a Chrome process maxing out a CPU core. Disabling Bypass Paywalls fixes it instantly, all pages trying to load finish loading.

**Comment by oredbored** [comment] 2020-04-26 11:52
Sorry about that. Here's the screenshot of Chrome's Task Manager. It took a few hours to reproduce the issue again, so I was wrong about it being every 15 minutes.

![screenshot2](https://user-images.githubusercontent.com/64238189/80306661-c1309280-8818-11ea-9522-aaf5bf1320e7.png)

**Comment by iamadamdev** [comment] 2020-04-26 18:21
What version of Chrome are you on?
@kimkha Have you seen anything like this before?
I will keep an eye out. I suspect something is getting stuck in an infinite loop somewhere.

**Comment by kimkha** [comment] 2020-04-26 23:58
I haven't met this issue, but I'm using Mac. Maybe it's Windows-specific?

**Comment by oredbored** [comment] 2020-04-27 01:44
Version 81.0.4044.122 (Official Build) (64-bit)
Thanks.

**Comment by iamadamdev** [comment] 2020-04-28 02:08
Try latest master and let me know if the issue persists.

**Comment by oredbored** [comment] 2020-04-28 05:55
So far so good. Will let you know if that changes. Thanks, it's much appreciated!

**Comment by fiveolddogs** [comment] 2020-04-29 00:04
I updated to the new 1.7.0 and the problem just occurred. This happens a few times randomly throughout the day. I keep the Chrome extensions page open in a tab, so when nothing will load, I just go to the extensions page and click the reload circle for Bypass Paywalls. Everything immediately works again.

**Comment by iamadamdev** [comment] 2020-04-29 00:06
@fiveolddogs 1.7.0 from the releases page or did you use latest master?

**Comment by fiveolddogs** [comment] 2020-04-29 00:09
Woops. I guess I didn't understand the terminology and didn't know there was a difference. I downloaded the zip given in the installation instructions on the main page -- https://github.com/iamadamdev/bypass-paywalls-chrome/archive/master.zip

**Comment by iamadamdev** [comment] 2020-04-29 00:23
That is correct. And I assume you're on Windows?

**Comment by oredbored** [comment] 2020-04-29 03:27
It took a long time but it happened again for me too. I am using the latest master. Chrome Task Manager was the same as before.

**Comment by fiveolddogs** [comment] 2020-04-29 04:11
Yes, Windows 10.

**Comment by iamadamdev** [comment] 2020-04-29 04:23
Made some performance improvements, please try again on latest master.

Every time it happened previously did you guys have a lot of tabs open? Or did you guys leave Chrome open for a long time? If so about how long?

**Comment by fiveolddogs** [comment] 2020-04-29 05:21
I do keep a lot of tabs open. I also have a lot of extensions. I have done some limited experiments disabling other extensions, but I have not noticed any other extension contributing to this issue.

I do keep Chrome open all the time, but I occasionally restart Chrome if I am having issues or when Chrome's memory usage creeps up too high. I have the Fail to Load issue happen within minutes of the restart, so long sessions do not appear to be part of the problem.

**Comment by oredbored** [comment] 2020-04-30 02:31
I usually have long sessions and a lot of tabs open, but the last time it happened I only had 2 or 3 tabs open. I will try the new version, thanks.

**Comment by kimkha** [comment] 2020-04-30 11:10
I just did some improvements on #601 

Let's see if Adam's happy with that. 😄

**Comment by iamadamdev** [comment] 2020-05-02 19:54
thanks @kimkha, I merged it

**Comment by fiveolddogs** [comment] 2020-05-02 19:58
I have been running the 4/28 master for four days, and so far so good. No hanging Chrome for me yet!

**Comment by iamadamdev** [comment] 2020-05-02 20:03
Thanks for the report!

**Comment by jrbarrick** [comment] 2020-05-02 23:25
Yep, all good here as well.  The first fix didn't help with the page that triggered the hang, but I've just tried the latest master again, and now everything is working fine.

**Comment by kimkha** [comment] 2020-05-02 23:28
So good to hear! 🎉

**Comment by oredbored** [comment] 2020-05-03 02:56
All good for me as well. Cheers guys.

**Closed** 2020-05-03 20:54 UTC
