### ISSUE TITLE
Firefox New Mobile App

### ISSUE THREAD

**Issue by atompilzli** [iamadamdev/bypass-paywalls-chrome#836] opened 2020-08-07 15:02 UTC
I love your firefox addon and it worked properly also on the android firefox app. But since the newest update of the firefox app, it doesn't work anymore. I'd love to see if you could fix that. Cheers Nick

**Comment by iamadamdev** [comment] 2020-08-07 20:00
https://blog.mozilla.org/addons/2020/02/11/faq-for-extension-support-in-new-firefox-for-android/
https://www.xda-developers.com/mozilla-firefox-79-for-android-preview-nightly-update-without-extensions-add-ons/

**Comment by TheW0LVERIN3** [comment] 2020-08-14 23:36
https://github.com/interfect/fenix
This is iceweasle, a fork of the new fenix browser which allows any add on in the firefox addon store to be added. Xpi files cannot be installed yet because fenix does not support it and the dev doesn't have the time. Have you considered putting your extension on the firefox add on site.

**Comment by bahari15** [comment] 2020-08-20 22:22
Seconding this.

> https://blog.mozilla.org/addons/2020/02/11/faq-for-extension-support-in-new-firefox-for-android/
> https://www.xda-developers.com/mozilla-firefox-79-for-android-preview-nightly-update-without-extensions-add-ons/
Wait so this means on the meantime we cannot use bypass paywall on firefox for android because the devs don't allow it?

**Comment by TheW0LVERIN3** [comment] 2020-08-21 07:32
You can always just download the fennec apk from apkmirror and use it with bypass paywalls when you come across a paywall until they add support for sideloading on the new fenix

**Comment by TheW0LVERIN3** [comment] 2020-08-21 07:38
It is not because the devs don't allow it, it is because no one has added the code for it yet and the guy who made the fork only keeps it updated and so the extension list keeps working and he sometimes adds (experimental)pull requests from fenix that haven't been merged in nightly yet. Someone just needs to work on adding support.

**Comment by goloskokovic** [comment] 2020-08-29 06:23
> You can always just download the fennec apk from apkmirror and use it with bypass paywalls when you come across a paywall until they add support for sideloading on the new fenix

https://www.apkmirror.com/apk/mozilla/firefox/firefox-68-11-0-release/firefox-browser-fast-private-68-11-0-2-android-apk-download/download/

**Comment by B0pol** [comment] 2020-09-03 17:33
https://blog.mozilla.org/addons/2020/09/02/update-on-extension-support-in-the-new-firefox-for-android/ announced to let nightly users to install from Firefox store this month, but they didn't mention xpi. 

@TheW0LVERIN3 Iceweasel only bypass the store restriction, but does not allow to install via xpi

https://github.com/interfect/fenix/issues/31

Iceweasel dev:
> Getting it in is going to require someone actually writing the UI to load an extension from XPI (or else standing up a fake addons.mozilla.org to host it and pointing the browser at it).
> I'd like to have it, but I don't think I can do it myself.

This https://github.com/mozilla-mobile/fenix/issues/11308 issue was about xpi addons installation, they closed as duplicate of https://github.com/mozilla-mobile/fenix/issues/14034

Then we'll have to wait again

**Comment by patfla** [comment] 2020-09-10 02:02
Do I take it correctly that the problem is that FF 80 won't load extensions from .xpi files?

**Comment by patfla** [comment] 2020-09-12 22:31
I'm a recently retired developer.  What, approximately, would be involved in modifying Bypass Paywalls for Android Firefox?

**Comment by iamadamdev** [comment] 2020-09-12 22:58
1. Don't upgrade your FF for Android
2. Or try https://github.com/fork-maintainers/iceweasel (no guarantees, haven't tested)

**Comment by patfla** [comment] 2020-09-12 23:56
I used apkmirror to return to a working version of FF.

**Comment by LimitedEdiition** [comment] 2020-09-13 23:37
I will try IceWeasel later tonight. In the meantime, what other browsers do you use on Android that work with this extension?

**Comment by TheW0LVERIN3** [comment] 2020-09-13 23:47
old firefox fennec and kiwi browser

**Comment by damocamo** [comment] 2020-09-15 00:38
How can you get this to work on kiwi?

**Comment by BeeeWall** [comment] 2020-09-29 21:52
Is it possible to make a userscript from this? The latest nightly can install any extension from AMO (with a couple hoops), so you can install a userscript extension, but not this one.

**Comment by LimitedEdiition** [comment] 2020-09-30 04:19
Has anyone tested this in IceRaven?

**Comment by PabloGrok** [comment] 2020-10-03 18:45
@iamadamdev 
>     1. Don't upgrade your FF for Android
> 
>     2. Or try https://github.com/fork-maintainers/iceweasel (no guarantees, haven't tested)

If you publish your addon on AMO, latest Firefox Nightly will be able to use it. (Check here: https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/ )

**Comment by iamadamdev** [comment] 2020-10-03 18:56
My addon used to be on AMO, Mozilla banned it. I am trying again now.

**Comment by LimitedEdiition** [comment] 2020-10-06 21:05
Any progress on this? Seems like Firefox is trying to find creative ways to make money, so maybe with a nice badge (aka bribe), we might be able to get this onto AMO quicker.

**Comment by iamadamdev** [comment] 2020-10-06 21:12
They replied saying the rejection stands.

**Comment by LimitedEdiition** [comment] 2020-10-06 21:31
Are these impersonators? 
https://addons.mozilla.org/en-GB/android/addon/bypass-paywalls-for-firefox/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search
https://addons.mozilla.org/en-GB/android/addon/bypass-paywalls-clean/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by iamadamdev** [comment] 2020-10-06 21:56
Yes, that person ripped off my repo

**Comment by iamadamdev** [comment] 2020-10-06 21:59
Yeah that seems like an impersonator. I wouldn't trust them.
The version shows `1.8.9.0`, I never updated the FF version to that.

**Comment by patfla** [comment] 2020-10-06 22:45
Are there other means by which bypass can be made installable into Android FF 80+?

**Comment by iamadamdev** [comment] 2020-10-06 23:34
@patfla Did you try iceraven-browser?

**Comment by patfla** [comment] 2020-10-06 23:42
No.  And you're right: I should have, and will, give it a try.

**Comment by PabloGrok** [comment] 2020-10-07 13:58
> Yeah that seems like an impersonator.

Sorry, but it looks like a legitimate fork to me. It's working fine with Firefox Nightly for Android and its developer is eager to help with issues. He solved mine in a couple of days. 

I don't know why his addon can be on AMO and yours not, but then I'm no developer and don't know AMO rules at all.

**Comment by BeeeWall** [comment] 2020-10-07 14:34
One of them tried to pretend to actually be the dev of this project. The other one seems to probably be a legit fork though.

**Comment by PabloGrok** [comment] 2020-10-07 14:38
I only found one project called "Bypass Paywalls Clean", by magnolia1234. He never pretended he's Adam. Don't know about any other project.

**Comment by BeeeWall** [comment] 2020-10-07 14:51
Yeah, that's the legit one. There's one just called "Bypass Paywalls", with the icon of this project, linking to this repo for the homepage, by a user named "iamadamdev", who is not actually Adam (because Mozilla won't let him upload it). That's the one that's presumably an imposter.

**Comment by patfla** [comment] 2020-10-07 19:55
> @patfla Did you try iceraven-browser?

Now installed and with bypass also installed.  Works well - thanks.

**Comment by ankitp4t3l** [comment] 2020-10-11 22:44
@patfla How were you able to install bypass (this repo's addon) into iceraven? I thought sideload support is not present?

**Comment by LimitedEdiition** [comment] 2020-10-13 06:29
Question for the developer, any chance you can port this onto the Samsung Internet browser for mobile. It's available on the app store for all Android devices, so many people will be able to access it. Just food for thought.

**Comment by B0pol** [comment] 2020-10-13 09:56
Because it's bypass paywall clean not this bypass paywall:

https://bitbucket.org/magnolia1234/bypass-paywalls-firefox-clean

https://addons.mozilla.org/fr/android/addon/bypass-paywalls-clean/

**Closed** 2020-11-12 02:00 UTC
