### ISSUE TITLE
New Zealand Herald: No longer able to access the premium content

### ISSUE THREAD

**Issue by Benoire** [iamadamdev/bypass-paywalls-chrome#984] opened 2020-10-23 22:03 UTC
Hi

The New Zealand Herald was working fine up until about 2 weeks ago and then a change they have made has stopped the ability for your excellent extension to work.  This is in Microsoft Edge Chromium with developer mode active but is the same as Chrome from my testing.

Example of a premium page: https://www.nzherald.co.nz/business/mary-holm-buy-that-car-cheque-or-no-cheque/DYLT537DKIFAPDPFBCG4HMLN7M/

Are you able to have a look?  The site developer clearly hadn't made a change in a while as the sites premium content was fully viewable during many new versions of your extension and has changed after your latest release so wasn't a change on your side!

Many thanks,

Chris

**Comment by iamadamdev** [comment] 2020-10-23 23:11
Still works for me on latest master (Chrome):
![image](https://user-images.githubusercontent.com/36013816/97061101-70d98980-154a-11eb-9a43-eae642f137d6.png)

**Comment by Benoire** [comment] 2020-10-24 06:27
Hmmm odd.  I've just reinstalled the latest compiled version and ensured that uBlock Origin is installed in Chrome this time... Won't let me view any premium pages.  What is the best method to trouble shoot?

**Comment by Selfy** [comment] 2020-10-24 19:25
Encountered the same issue on firefox, cant access nzherald premium content. Ensured addons was up to date, still no luck.

**Comment by anotherdave** [comment] 2020-10-24 22:59
Reproduced this with another article on the latest release version 1.7.6, but fixed in latest version from Git source, so needs another release to fix. Workaround is to use the [Git source](https://github.com/iamadamdev/bypass-paywalls-chrome/archive/master.zip).

**Comment by mentalinc** [comment] 2020-10-26 06:42
Great thanks, that seems to have fixed it for me as well.

**Comment by iamadamdev** [comment] 2020-10-27 04:38
Released updated FF version. https://github.com/iamadamdev/bypass-paywalls-chrome/releases/tag/v1.7.7

**Closed** 2020-10-27 04:38 UTC
